/**
 * Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
    Hackthebox_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'Hackthebox'
        }
    ],
    Yunjing_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'Yunjing'
        }
    ],
    HackMyVM_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'HackMyVM'
        }
    ],
    ToolsGuide_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'ToolsGuide'
        }
    ],
    // 接下来的为 Hackmyvm 部分的自动索引生成
    docs: [
        {
            type: 'category',
            label: 'Guides',
            link: {
                type: 'generated-index',
                title: 'Docusaurus Guides',
                description: 'Learn about the most important Docusaurus concepts!',
                slug: '/HackMyVM/Challenges/Crypto',
                keywords: ['HMV-Challenges'],
            },
            items: [],
        },
    ],
};

export default sidebars;
