/**
 * Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    HackTheBox_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'HackTheBox'
        }
    ],
    Yunjing_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'Yunjing'
        }
    ],
    HackMyVM_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'HackMyVM'
        },
    ],
    Xuanji_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'Xuanji'
        },
    ],
    Independent_Environment_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'Independent-Environment'
        }
    ],
    ToolsGuide_Sidebar: [
        {
            type: 'autogenerated',
            dirName: 'ToolsGuide'
        }
    ],

};

export default sidebars;
